---

#=======================================================================
# Global stuff
stages:
  - 'sanity'
  - 'lint'
  - 'unit'
  - 'acceptance'
  - 'deployment'

# Default versions are set only as fallbacks for jobs that don't care which
# version they use.  Versions should be explicitly set in any job with specific
# version requirements, even if they match these defaults.
image: 'ruby:2.1'
variables:
  PUPPET_VERSION: '~> 4.10.0'
  BUNDLER_VERSION: '1.16.1'
  MODULE_NAME: "$(ruby -r json -e 'JSON.load(File.read('metadata.json'))['name']')"
  MODULE_VERSION: "$(ruby -r json -e 'JSON.load(File.read('metadata.json'))['version']')"

before_script:
  - 'ruby -v'
  - 'gem list -ie --silent -v "$BUNDLER_VERSION" bundler && bundle -v || gem install bundler --no-document -v "$BUNDLER_VERSION"'
  - 'bundle install -j $(nproc) --no-binstubs --path vendor'

cache:
  key: '${CI_COMMIT_REF_SLUG}'
  paths:
    - 'vendor/ruby'

#=======================================================================
# Anchors

.lint_base: &lint_base
  stage: 'lint'
  tags: ['docker']
  script:
    - 'bundle exec rake syntax'
    - 'bundle exec rake lint'
  cache:
    policy: 'pull'
  dependencies: []
  artifacts:
    when: 'always'
    paths:
      - 'Gemfile.lock'

.unit_base: &unit_base
  stage: 'unit'
  tags: ['docker']
  script:
    - 'bundle exec rake spec'
  cache:
    policy: 'pull'
  dependencies: []
  artifacts:
    when: 'always'
    paths:
      - 'Gemfile.lock'

.acceptance_base: &acceptance_base
  stage: 'acceptance'
  tags: ['beaker']
  cache:
    policy: 'pull'
  dependencies: []
  artifacts:
    when: 'always'
    paths:
      - 'Gemfile.lock'

# ----------------------------------------------------------------------
# Version Matrix
#
# It would be too expensive, both in time and compute resources, to test
# against every last version combination, so we restrict it to this subset.
# Version sets are selected based on current support policies for major platform
# software, such as Puppet and Ruby.  Namely, we use the version combinations
# bundled in Puppet Enterprise.
#
# For more information see:
#  * https://puppet.com/docs/pe/latest/overview/component_versions_in_recent_pe_releases.html
#  * https://puppet.com/misc/puppet-enterprise-lifecycle
#  * https://puppet.com/docs/pe/latest/overview/getting_support_for_pe.html#standard-releases-and-long-term-support-releases
#
# ----------------------------------------------
# | Release | Puppet | Ruby | End-of-Life Date |
# ----------|--------|------|------------------|
# PE 2016.4   4.7      2.1    2018-10
# PE 2016.5   4.8      2.1    2017-05
# SIMP 6.0    4.8      2.1    TBD
# PE 2017.1   4.9      2.1    2017-10
# PE 2017.2   4.10     2.1    2018-02
# PE 2017.3   5.3      2.4    2018-08
# PE 2018.1   5.5      2.4    2020-05
#

.pe_2016_4: &pe_2016_4
  variables:
    PUPPET_VERSION: '~> 4.10.0'
    BEAKER_PUPPET_COLLECTION: 'pc1'
    BEAKER_PUPPET_AGENT_VERSION: '~> 1.10.0'

.pe_2016_5: &pe_2016_5
  variables:
    PUPPET_VERSION: '~> 4.8.1'
    BEAKER_PUPPET_COLLECTION: 'pc1'
    BEAKER_PUPPET_AGENT_VERSION: '~> 1.8.2'

.simp_6: &simp_6
  variables:
    PUPPET_VERSION: '~> 4.8.1'
    BEAKER_PUPPET_COLLECTION: 'pc1'
    BEAKER_PUPPET_AGENT_VERSION: '~> 1.8.2'

.pe_2017_1: &pe_2017_1
  variables:
    PUPPET_VERSION: '~> 4.9.4'
    BEAKER_PUPPET_COLLECTION: 'pc1'
    BEAKER_PUPPET_AGENT_VERSION: '~> 1.9.3'

.pe_2017_2: &pe_2017_2
  variables:
    PUPPET_VERSION: '~> 4.10.1'
    BEAKER_PUPPET_COLLECTION: 'pc1'
    BEAKER_PUPPET_AGENT_VERSION: '~> 1.10.1'

.pe_2017_3: &pe_2017_3
  variables:
    PUPPET_VERSION: '~> 5.3.2'
    BEAKER_PUPPET_COLLECTION: 'puppet5'
    BEAKER_PUPPET_AGENT_VERSION: '~> 5.3.2'

.pe_2018_1: &pe_2018_1
  variables:
    PUPPET_VERSION: '~> 5.5.1'
    BEAKER_PUPPET_COLLECTION: 'puppet5'
    BEAKER_PUPPET_AGENT_VERSION: '~> 5.5.1'

.pup_5_latest: &pup_5_latest
  variables:
    PUPPET_VERSION: '~> 5.0'
    BEAKER_PUPPET_COLLECTION: 'puppet5'
    BEAKER_PUPPET_AGENT_VERSION: '~> 5.0'


#=======================================================================
# Basic Sanity Checks
#

# Execute simple sanity checks on the environment before proceeding to more
# resource-intensive jobs.  Besides running checks, this condenses the initial
# cache generation into a single job for the later stages.  The first stage,
# in particular, would otherwise suffer a heavy cache-miss penalty as its
# jobs kick off in parallel.
sanity_checks:
  stage: 'sanity'
  tags: ['docker']
  script:
    - 'bundle exec rake check:dot_underscore'
    - 'bundle exec rake check:test_file'
    - 'bundle exec rake pkg:check_version'
    - 'bundle exec rake pkg:compare_latest_tag'

tag_check:
  stage: 'sanity'
  only: ['tags']
  tags: ['docker']
  script: '[ "$CI_COMMIT_TAG" = "$MODULE_VERSION" ] || echo "ERROR: Tag does not match metadata version" && exit 1'


#=======================================================================
# Lint Tests
#

# Linting, for the most part, isn't affected by version changes in Puppet,
# so we only test against the latest version for each MAJOR release.
pup4_x-lint:
  <<: *lint_base
  image: 'ruby:2.1'
  variables:
    PUPPET_VERSION: '~> 4.0'

pup5_x-lint:
  <<: *lint_base
  image: 'ruby:2.4'
  variables:
    PUPPET_VERSION: '~> 5.0'

#=======================================================================
# Unit Test Matrix
#

# ----------------------------------------------------------------------
# Puppet 4.7 for PE 2016.4 LTS Support (EOL: 2018-10)
pup4_7-unit:
  <<: *unit_base
  <<: *pe_2016_4
  image: 'ruby:2.1'

# ----------------------------------------------------------------------
# Puppet 4.8 for SIMP 6 (EOL: TBD) and PE 2016.5 (EOL: 2017-04)
pup4_8-unit:
  <<: *unit_base
  <<: *pe_2016_5
  image: 'ruby:2.1'

# ----------------------------------------------------------------------
# Puppet 4.10 for PE 2017.2 support (EOL:2018-02)
pup4_10-unit:
  <<: *unit_base
  <<: *pe_2017_2
  image: 'ruby:2.1'

# ----------------------------------------------------------------------
# Puppet 5.3 for PE 2017.3 support (EOL: 2018-07)
pup5_3-unit:
  <<: *unit_base
  <<: *pe_2017_3
  image: 'ruby:2.4'

# ----------------------------------------------------------------------
# Puppet 5.5 for PE 2018.1 LTS support (EOL: 2020-05)
pup5_5-unit:
  <<: *unit_base
  <<: *pe_2018_1
  image: 'ruby:2.4'

# ----------------------------------------------------------------------
# Keep an eye on the latest Puppet 5.x release
pup5_latest-unit:
  <<: *unit_base
  image: 'ruby:2.4'
  variables:
    PUPPET_VERSION: '~> 5.0'


# ==============================================================================
# Acceptance tests
#

# ----------------------------------------------------------------------
# Puppet 4.8 for SIMP 6 (EOL: TBD) and PE 2016.5 (EOL: 2017-04)
el-pup4_8-default:
  <<: *acceptance_base
  <<: *simp_6
  script:
    - 'bundle exec rake beaker:suites'

el-pup4_8-default-fips:
  <<: *acceptance_base
  <<: *simp_6
  variables:
    BEAKER_fips: 'yes'
  script:
    - 'bundle exec rake beaker:suites'

# ----------------------------------------------------------------------
# Puppet 5.5 for PE 2018.1 LTS support (EOL: 2020-05)
el-pup5_5-default:
  <<: *acceptance_base
  <<: *pe_2018_1
  script:
    - 'bundle exec rake beaker:suites'

el-pup5_5-default-fips:
  <<: *acceptance_base
  <<: *pe_2018_1
  variables:
    BEAKER_fips: 'yes'
  script:
    - 'bundle exec rake beaker:suites'

# vi:tabstop=2:shiftwidth=2:expandtab
